language: php
php:
- '7.2'
branches:
  only:
  - master
#addons:
#  mariadb: '10.2'
env:
# in sequence :
# get the directory name after the sign "-"
# "git for-each-ref --sort=-taggerdate --count=1 --format '%(refname:short)' refs/tags" displays the last tag's shortname
# "git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:subject)' refs/tags" displays the last tag's first line
# "git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:body)' refs/tags" displays the last tag's 3d line and following ones
>
  - GLPI_PLUGIN_NAME=`echo $TRAVIS_BUILD_DIR | sed -e 's/^.*-//'`
    TRAVIS_TAG=`git for-each-ref --sort=-taggerdate --count=1 --format '%(refname:short)' refs/tags`
    RELEASE_NAME=`git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:subject)' refs/tags`
    RELEASE_BODY=`git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:body)' refs/tags`
install: true
script: true
after_success:
- tar --transform "s%^%$GLPI_PLUGIN_NAME/%" --show-transformed -zcvf $GLPI_PLUGIN_NAME-$TRAVIS_TAG.tar.gz ajax front inc locales sql bp.png *.xml *.php  LICENSE README.md
deploy:
  provider: releases
  token:
    secure: bceSLbOpkmLQmoVgTYJX7zzHQf9qpAW76RB/8EVbLU1YnrPUrJIVo35jw6pT33XEsxXTKAX6iLIGy/BPGCLQJf8Oo0f2k5LIk+YmSZuKgPp1ibbUzbXtHart+CE0DGWkoohMdMPcPeV4bF0glZmZO6Ejp4zR4CnBvQyvaGKL+hXLSSiqZSVx9Ix+bW4WtlkRgj/EwuQTSySUX+tbO1WTgdcYLNwneQuoGN6JX7r74PDBtXDp9Nzl3MK/Vequ+O498a2w+g6TyufA/xOSWOQxeo+Yk5sjczT2l9oFJ1e8HnGTQVfESAs4DND/Rd7XOcGtvLXVSS17m18PuhP2gNBDsLgkNAeBGD0DpjORUpFlRw5v8N7vTxWSfenBAEg4JOCfLKLmEqayYI+SHdVGQWGXTR93U/wdYezMDkoYErQ+s+XaTgTI3ChV2jN1facTqFAMPunGhu+PVs1T0RuXCRM/B72sPLIEeh2AWnj/G1ri6mnjxxc0w1yuCEpMj34Sn/zCBP9xLFIkm3Mn9+lBVC3VUQA9tcYWD7TpctQZOELPlac4AS5P3pJK2zjVOqakpeCisGyRRufAvxv71Kcz3LF4WHgRWKgJV5Z4e6e8YQYe4RPFythP3Si5/E5TF9oyJJTIv2F4z+tRYGS8vVzzyoGsKR+Wak5Gtfvn4dbarsxpJwU=
  skip_cleanup: true
  file: $GLPI_PLUGIN_NAME-$TRAVIS_TAG.tar.gz
  name: $RELEASE_NAME
  release_notes: $RELEASE_BODY
  prerelease: false
  on:
    repo: ericferon/glpi-$GLPI_PLUGIN_NAME
    tags: true
